#ifndef _DEFINES_H
#define _DEFINES_H
#define SETBIT(WORD,BITPOS) (WORD|=(1<<BITPOS))
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))
#define CPLBIT(WORD,BITPOS) (WORD^=(1<<BITPOS))

#define READBIT(WORD,BITPOS)((WORD>>BITPOS)&1)
#define WRITEBYTE(WORD,SBITPOS,DATA)\
 (WORD=((WORD & ~(255<<SBITPOS))|(DATA<<SBITPOS)))
#define WRITENIBBLE(WORD,SBITPOS,DATA)\
 (WORD=((WORD & ~(15<<SBITPOS))|(DATA<<SBITPOS)))

#define WRITEBIT(WORD,SBITPOS,DATA) \
	(WORD=((WORD&~(1<<SBITPOS))|(DATA<<SBITPOS)));

#define SSETBIT(WORD,BITPOS) (WORD=(1<<BITPOS))	//IOSET SFRS
#define SCLRBIT SSETBIT	  //IOCLR SFRS
#endif
